#pragma once

#include <Arduino.h>

/******************************************************************************/
/* PRIMITIVES                                                                 */
/******************************************************************************/

void next(void);
void accep();
void qrx(void);
void txsto(void);
void docon(void);
void dolit(void);
void dolist(void);
void exitt(void);
void execu(void);
void donext(void);
void qbran(void);
void bran(void);
void store(void);
void at(void);
void cstor(void);
void cat(void);
void rpat(void);
void rpsto(void);
void rfrom(void);
void rat(void);
void tor(void);
void spat(void);
void spsto(void);
void drop(void);
void dup(void);
void swap(void);
void over(void);
void zless(void);
void andd(void);
void orr(void);
void xorr(void);
void uplus(void);
void nop(void);
void qdup(void);
void rot(void);
void ddrop(void);
void ddup(void);
void plus(void);
void inver(void);
void negat(void);
void dnega(void);
void subb(void);
void abss(void);
void great(void);
void less(void);
void equal(void);
void uless(void);
void ummod(void);
void msmod(void);
void slmod(void);
void mod(void);
void slash(void);
void umsta(void);
void star(void);
void mstar(void);
void ssmod(void);
void stasl(void);
void pick(void);
void pstor(void);
void dstor(void);
void dat(void);
void count(void);
void dovar(void);
void maxx(void);
void minn(void);
void sendPacket(void);
void poke(void);
void peeek(void);
void adc(void);

extern void (*primitives[72])(void);
extern int as_nop;
extern int as_accept;
extern int as_qrx;
extern int as_txsto;
extern int as_docon;
extern int as_dolit;
extern int as_dolist;
extern int as_exit;
extern int as_execu;
extern int as_donext;
extern int as_qbran;
extern int as_bran;
extern int as_store;
extern int as_at;
extern int as_cstor;
extern int as_cat;
extern int as_rpat;
extern int as_rpsto;
extern int as_rfrom;
extern int as_rat;
extern int as_tor;
extern int as_spat;
extern int as_spsto;
extern int as_drop;
extern int as_dup;
extern int as_swap;
extern int as_over;
extern int as_zless;
extern int as_andd;
extern int as_orr;
extern int as_xorr;
extern int as_uplus;
extern int as_next;
extern int as_qdup;
extern int as_rot;
extern int as_ddrop;
extern int as_ddup;
extern int as_plus;
extern int as_inver;
extern int as_negat;
extern int as_dnega;
extern int as_subb;
extern int as_abss;
extern int as_equal;
extern int as_uless;
extern int as_less;
extern int as_ummod;
extern int as_msmod;
extern int as_slmod;
extern int as_mod;
extern int as_slash;
extern int as_umsta;
extern int as_star;
extern int as_mstar;
extern int as_ssmod;
extern int as_stasl;
extern int as_pick;
extern int as_pstor;
extern int as_dstor;
extern int as_dat;
extern int as_count;
extern int as_dovar;
extern int as_max;
extern int as_min;
extern int as_tone; //
extern int as_sendPacket;
extern int as_poke;
extern int as_peek;
extern int as_adc;
extern int as_pin; //
extern int as_duty; //
extern int as_freq; //
